// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmsteqiyveyxtcuiqieh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imptc3RlcWl5dmV5eHRjdWlxaWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODM5NzIsImV4cCI6MjA1OTM1OTk3Mn0.KC9c44SRs5WUUd2fawaxp9CyT81PWNh8MuUYb7IJxZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);